# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainFrame.ui'
#
# Created: Thu Mar 25 20:39:28 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_TabWidget_MainFrame(object):
    def setupUi(self, TabWidget_MainFrame):
        TabWidget_MainFrame.setObjectName("TabWidget_MainFrame")
        TabWidget_MainFrame.setWindowModality(QtCore.Qt.ApplicationModal)
        TabWidget_MainFrame.resize(667, 424)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TabWidget_MainFrame.sizePolicy().hasHeightForWidth())
        TabWidget_MainFrame.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/tux_linux_inside_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidget_MainFrame.setWindowIcon(icon)
        TabWidget_MainFrame.setToolTip("")
        TabWidget_MainFrame.setStyleSheet("None")
        TabWidget_MainFrame.setMovable(True)
        self.tab_MainFrame = QtGui.QWidget()
        self.tab_MainFrame.setToolTip("")
        self.tab_MainFrame.setObjectName("tab_MainFrame")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_MainFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_ConnDiscon = QtGui.QPushButton(self.tab_MainFrame)
        self.pushButton_ConnDiscon.setObjectName("pushButton_ConnDiscon")
        self.gridLayout_2.addWidget(self.pushButton_ConnDiscon, 0, 0, 1, 1)
        self.pushButton_DNSelected = QtGui.QPushButton(self.tab_MainFrame)
        self.pushButton_DNSelected.setObjectName("pushButton_DNSelected")
        self.gridLayout_2.addWidget(self.pushButton_DNSelected, 0, 1, 1, 1)
        self.pushButton_UnMark = QtGui.QPushButton(self.tab_MainFrame)
        self.pushButton_UnMark.setObjectName("pushButton_UnMark")
        self.gridLayout_2.addWidget(self.pushButton_UnMark, 0, 2, 2, 1)
        self.progressBar = QtGui.QProgressBar(self.tab_MainFrame)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 0, 3, 1, 1)
        self.pushButton_Quit = QtGui.QPushButton(self.tab_MainFrame)
        self.pushButton_Quit.setObjectName("pushButton_Quit")
        self.gridLayout_2.addWidget(self.pushButton_Quit, 0, 4, 1, 1)
        self.pushButton_AdminPanel = QtGui.QPushButton(self.tab_MainFrame)
        self.pushButton_AdminPanel.setObjectName("pushButton_AdminPanel")
        self.gridLayout_2.addWidget(self.pushButton_AdminPanel, 1, 0, 1, 2)
        self.pushButton_Author = QtGui.QPushButton(self.tab_MainFrame)
        self.pushButton_Author.setObjectName("pushButton_Author")
        self.gridLayout_2.addWidget(self.pushButton_Author, 1, 4, 1, 1)
        self.dockWidget_SharedByServer = QtGui.QDockWidget(self.tab_MainFrame)
        self.dockWidget_SharedByServer.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dockWidget_SharedByServer.setAutoFillBackground(False)
        self.dockWidget_SharedByServer.setFloating(True)
        self.dockWidget_SharedByServer.setObjectName("dockWidget_SharedByServer")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.tableWidget_SharedByServer = QtGui.QTableWidget(self.dockWidgetContents_2)
        self.tableWidget_SharedByServer.setGeometry(QtCore.QRect(0, 0, 661, 151))
        self.tableWidget_SharedByServer.setProperty("showDropIndicator", False)
        self.tableWidget_SharedByServer.setDragDropOverwriteMode(False)
        self.tableWidget_SharedByServer.setAlternatingRowColors(True)
        self.tableWidget_SharedByServer.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tableWidget_SharedByServer.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_SharedByServer.setColumnCount(7)
        self.tableWidget_SharedByServer.setObjectName("tableWidget_SharedByServer")
        self.tableWidget_SharedByServer.setColumnCount(7)
        self.tableWidget_SharedByServer.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedByServer.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedByServer.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedByServer.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedByServer.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedByServer.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedByServer.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedByServer.setHorizontalHeaderItem(6, item)
        self.dockWidget_SharedByServer.setWidget(self.dockWidgetContents_2)
        self.gridLayout_2.addWidget(self.dockWidget_SharedByServer, 2, 0, 1, 5)
        self.dockWidget = QtGui.QDockWidget(self.tab_MainFrame)
        self.dockWidget.setFloating(True)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.scrollArea_Console = QtGui.QScrollArea(self.dockWidgetContents_4)
        self.scrollArea_Console.setGeometry(QtCore.QRect(0, 0, 661, 101))
        self.scrollArea_Console.setWidgetResizable(True)
        self.scrollArea_Console.setObjectName("scrollArea_Console")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea_Console)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 657, 97))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_Console.setWidget(self.scrollAreaWidgetContents)
        self.dockWidget.setWidget(self.dockWidgetContents_4)
        self.gridLayout_2.addWidget(self.dockWidget, 3, 0, 1, 5)
        TabWidget_MainFrame.addTab(self.tab_MainFrame, "")
        self.tab_Shared = QtGui.QWidget()
        self.tab_Shared.setToolTip("")
        self.tab_Shared.setObjectName("tab_Shared")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_Shared)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dockWidget_2 = QtGui.QDockWidget(self.tab_Shared)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.tableWidget_SharedFileByMySelf = QtGui.QTableWidget(self.dockWidgetContents_6)
        self.tableWidget_SharedFileByMySelf.setGeometry(QtCore.QRect(0, 0, 661, 241))
        self.tableWidget_SharedFileByMySelf.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.tableWidget_SharedFileByMySelf.setAlternatingRowColors(True)
        self.tableWidget_SharedFileByMySelf.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tableWidget_SharedFileByMySelf.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_SharedFileByMySelf.setColumnCount(7)
        self.tableWidget_SharedFileByMySelf.setObjectName("tableWidget_SharedFileByMySelf")
        self.tableWidget_SharedFileByMySelf.setColumnCount(7)
        self.tableWidget_SharedFileByMySelf.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedFileByMySelf.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedFileByMySelf.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedFileByMySelf.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedFileByMySelf.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedFileByMySelf.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedFileByMySelf.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedFileByMySelf.setHorizontalHeaderItem(6, item)
        self.dockWidget_2.setWidget(self.dockWidgetContents_6)
        self.gridLayout_3.addWidget(self.dockWidget_2, 0, 0, 1, 4)
        self.pushButton_ADD = QtGui.QPushButton(self.tab_Shared)
        self.pushButton_ADD.setObjectName("pushButton_ADD")
        self.gridLayout_3.addWidget(self.pushButton_ADD, 1, 0, 1, 1)
        self.pushButton_Del = QtGui.QPushButton(self.tab_Shared)
        self.pushButton_Del.setObjectName("pushButton_Del")
        self.gridLayout_3.addWidget(self.pushButton_Del, 1, 1, 1, 1)
        self.pushButton_DELALL = QtGui.QPushButton(self.tab_Shared)
        self.pushButton_DELALL.setObjectName("pushButton_DELALL")
        self.gridLayout_3.addWidget(self.pushButton_DELALL, 1, 2, 1, 1)
        self.progressBar_2 = QtGui.QProgressBar(self.tab_Shared)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout_3.addWidget(self.progressBar_2, 1, 3, 1, 1)
        TabWidget_MainFrame.addTab(self.tab_Shared, "")
        self.tab_Options = QtGui.QWidget()
        self.tab_Options.setToolTip("")
        self.tab_Options.setObjectName("tab_Options")
        self.gridLayout = QtGui.QGridLayout(self.tab_Options)
        self.gridLayout.setObjectName("gridLayout")
        self.dockWidget_Connect = QtGui.QDockWidget(self.tab_Options)
        self.dockWidget_Connect.setAcceptDrops(False)
        self.dockWidget_Connect.setFloating(False)
        self.dockWidget_Connect.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_Connect.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_Connect.setObjectName("dockWidget_Connect")
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.lineEdit_IP = QtGui.QLineEdit(self.dockWidgetContents_5)
        self.lineEdit_IP.setGeometry(QtCore.QRect(0, 0, 191, 26))
        self.lineEdit_IP.setMaxLength(16)
        self.lineEdit_IP.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_IP.setObjectName("lineEdit_IP")
        self.lineEdit_Port = QtGui.QLineEdit(self.dockWidgetContents_5)
        self.lineEdit_Port.setGeometry(QtCore.QRect(0, 30, 191, 26))
        self.lineEdit_Port.setInputMask("")
        self.lineEdit_Port.setMaxLength(8)
        self.lineEdit_Port.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Port.setObjectName("lineEdit_Port")
        self.dockWidget_Connect.setWidget(self.dockWidgetContents_5)
        self.gridLayout.addWidget(self.dockWidget_Connect, 0, 0, 1, 1)
        self.dockWidget_3 = QtGui.QDockWidget(self.tab_Options)
        self.dockWidget_3.setFloating(False)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_8 = QtGui.QWidget()
        self.dockWidgetContents_8.setObjectName("dockWidgetContents_8")
        self.checkBox = QtGui.QCheckBox(self.dockWidgetContents_8)
        self.checkBox.setGeometry(QtCore.QRect(0, 0, 92, 23))
        self.checkBox.setObjectName("checkBox")
        self.dockWidget_3.setWidget(self.dockWidgetContents_8)
        self.gridLayout.addWidget(self.dockWidget_3, 0, 1, 2, 1)
        self.dockWidget_ServAuth = QtGui.QDockWidget(self.tab_Options)
        self.dockWidget_ServAuth.setFloating(False)
        self.dockWidget_ServAuth.setObjectName("dockWidget_ServAuth")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.lineEdit_Login = QtGui.QLineEdit(self.dockWidgetContents)
        self.lineEdit_Login.setGeometry(QtCore.QRect(0, 0, 191, 26))
        self.lineEdit_Login.setMaxLength(16)
        self.lineEdit_Login.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Login.setObjectName("lineEdit_Login")
        self.lineEdit_2 = QtGui.QLineEdit(self.dockWidgetContents)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 30, 191, 26))
        self.lineEdit_2.setMaxLength(16)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.dockWidget_ServAuth.setWidget(self.dockWidgetContents)
        self.gridLayout.addWidget(self.dockWidget_ServAuth, 1, 0, 1, 1)
        TabWidget_MainFrame.addTab(self.tab_Options, "")
        self.tab_ProjectSite = QtGui.QWidget()
        self.tab_ProjectSite.setObjectName("tab_ProjectSite")
        self.webView_ProjectSite = QtWebKit.QWebView(self.tab_ProjectSite)
        self.webView_ProjectSite.setGeometry(QtCore.QRect(0, 0, 661, 391))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView_ProjectSite.sizePolicy().hasHeightForWidth())
        self.webView_ProjectSite.setSizePolicy(sizePolicy)
        self.webView_ProjectSite.setAcceptDrops(False)
        self.webView_ProjectSite.setUrl(QtCore.QUrl("http://github.com/str0g/PAPServer"))
        self.webView_ProjectSite.setObjectName("webView_ProjectSite")
        TabWidget_MainFrame.addTab(self.tab_ProjectSite, "")

        self.retranslateUi(TabWidget_MainFrame)
        TabWidget_MainFrame.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton_Quit, QtCore.SIGNAL("clicked()"), TabWidget_MainFrame.close)
        QtCore.QMetaObject.connectSlotsByName(TabWidget_MainFrame)

    def retranslateUi(self, TabWidget_MainFrame):
        TabWidget_MainFrame.setWindowTitle(QtGui.QApplication.translate("TabWidget_MainFrame", "myClient", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ConnDiscon.setToolTip(QtGui.QApplication.translate("TabWidget_MainFrame", "Połącz/rozłacz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ConnDiscon.setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Połącz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DNSelected.setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Pobierz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_UnMark.setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Odznacz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Quit.setToolTip(QtGui.QApplication.translate("TabWidget_MainFrame", "Wyjście", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Quit.setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Wyjście", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_AdminPanel.setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Panel administracyjny", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Author.setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Autor", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_SharedByServer.setWindowTitle(QtGui.QApplication.translate("TabWidget_MainFrame", "Lista Plików udostępnianych przez Serwer", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedByServer.setSortingEnabled(True)
        self.tableWidget_SharedByServer.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Pełna ścieżka", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedByServer.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Nazwa Pliku", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedByServer.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Rozmiar", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedByServer.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedByServer.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("TabWidget_MainFrame", "MD5", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedByServer.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Pobierane", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("TabWidget_MainFrame", "Konsola działań klient serwer", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget_MainFrame.setTabText(TabWidget_MainFrame.indexOf(self.tab_MainFrame), QtGui.QApplication.translate("TabWidget_MainFrame", "Strona główna", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_2.setWindowTitle(QtGui.QApplication.translate("TabWidget_MainFrame", "Udostępniane Pliki", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedFileByMySelf.setSortingEnabled(True)
        self.tableWidget_SharedFileByMySelf.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Pełna ścieżka", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedFileByMySelf.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Nazwa Pliku", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedFileByMySelf.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Rozmiar", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedFileByMySelf.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedFileByMySelf.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("TabWidget_MainFrame", "MD5", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedFileByMySelf.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Pobierane", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedFileByMySelf.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Ilosc klientów", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ADD.setToolTip(QtGui.QApplication.translate("TabWidget_MainFrame", "Dodaj pliki do listy udostępnionych", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ADD.setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Dodaj", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Del.setToolTip(QtGui.QApplication.translate("TabWidget_MainFrame", "Usuń pliki z listy udostępnionych", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Del.setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Usun", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DELALL.setToolTip(QtGui.QApplication.translate("TabWidget_MainFrame", "Wyczyść listę", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DELALL.setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Wyczyść listę", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget_MainFrame.setTabText(TabWidget_MainFrame.indexOf(self.tab_Shared), QtGui.QApplication.translate("TabWidget_MainFrame", "Udostępniane", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_Connect.setWindowTitle(QtGui.QApplication.translate("TabWidget_MainFrame", "Adres Serwera", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_IP.setToolTip(QtGui.QApplication.translate("TabWidget_MainFrame", "Wprowadź login", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_IP.setText(QtGui.QApplication.translate("TabWidget_MainFrame", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Port.setText(QtGui.QApplication.translate("TabWidget_MainFrame", "6666", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_3.setWindowTitle(QtGui.QApplication.translate("TabWidget_MainFrame", "Opcje", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("TabWidget_MainFrame", "Jakisc chBoxx", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_ServAuth.setWindowTitle(QtGui.QApplication.translate("TabWidget_MainFrame", "Autoryzacja", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Login.setToolTip(QtGui.QApplication.translate("TabWidget_MainFrame", "Wprowadź login", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Login.setText(QtGui.QApplication.translate("TabWidget_MainFrame", "user", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setText(QtGui.QApplication.translate("TabWidget_MainFrame", "password", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget_MainFrame.setTabText(TabWidget_MainFrame.indexOf(self.tab_Options), QtGui.QApplication.translate("TabWidget_MainFrame", "Opcje", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget_MainFrame.setTabText(TabWidget_MainFrame.indexOf(self.tab_ProjectSite), QtGui.QApplication.translate("TabWidget_MainFrame", "Strona Projektu", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
