# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainFrameRev2.ui'
#
# Created: Mon Jun 14 10:29:51 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 596)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 881, 321))
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_connection = QtGui.QWidget()
        self.tab_connection.setObjectName("tab_connection")
        self.dockWidget_SharedByServer = QtGui.QDockWidget(self.tab_connection)
        self.dockWidget_SharedByServer.setGeometry(QtCore.QRect(0, 74, 873, 211))
        self.dockWidget_SharedByServer.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dockWidget_SharedByServer.setAutoFillBackground(False)
        self.dockWidget_SharedByServer.setFloating(False)
        self.dockWidget_SharedByServer.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_SharedByServer.setObjectName("dockWidget_SharedByServer")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_SharedByServer = QtGui.QTableWidget(self.dockWidgetContents_2)
        self.tableWidget_SharedByServer.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.tableWidget_SharedByServer.setProperty("showDropIndicator", False)
        self.tableWidget_SharedByServer.setDragDropOverwriteMode(False)
        self.tableWidget_SharedByServer.setAlternatingRowColors(True)
        self.tableWidget_SharedByServer.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tableWidget_SharedByServer.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_SharedByServer.setColumnCount(6)
        self.tableWidget_SharedByServer.setObjectName("tableWidget_SharedByServer")
        self.tableWidget_SharedByServer.setColumnCount(6)
        self.tableWidget_SharedByServer.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedByServer.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedByServer.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedByServer.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedByServer.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedByServer.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedByServer.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedByServer.setHorizontalHeaderItem(5, item)
        self.tableWidget_SharedByServer.horizontalHeader().setDefaultSectionSize(120)
        self.verticalLayout_2.addWidget(self.tableWidget_SharedByServer)
        self.dockWidget_SharedByServer.setWidget(self.dockWidgetContents_2)
        self.pushButton_Search = QtGui.QPushButton(self.tab_connection)
        self.pushButton_Search.setGeometry(QtCore.QRect(182, 43, 85, 27))
        self.pushButton_Search.setObjectName("pushButton_Search")
        self.lineEdit_Search = QtGui.QLineEdit(self.tab_connection)
        self.lineEdit_Search.setGeometry(QtCore.QRect(279, 43, 503, 27))
        self.lineEdit_Search.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Search.setDragEnabled(True)
        self.lineEdit_Search.setObjectName("lineEdit_Search")
        self.pushButton_Quit = QtGui.QPushButton(self.tab_connection)
        self.pushButton_Quit.setGeometry(QtCore.QRect(788, 10, 85, 27))
        self.pushButton_Quit.setObjectName("pushButton_Quit")
        self.pushButton_UnMark = QtGui.QPushButton(self.tab_connection)
        self.pushButton_UnMark.setGeometry(QtCore.QRect(182, 10, 85, 27))
        self.pushButton_UnMark.setObjectName("pushButton_UnMark")
        self.pushButton_DNSelected = QtGui.QPushButton(self.tab_connection)
        self.pushButton_DNSelected.setGeometry(QtCore.QRect(91, 10, 85, 27))
        self.pushButton_DNSelected.setObjectName("pushButton_DNSelected")
        self.pushButton_AdminPanel = QtGui.QPushButton(self.tab_connection)
        self.pushButton_AdminPanel.setGeometry(QtCore.QRect(0, 43, 176, 27))
        self.pushButton_AdminPanel.setObjectName("pushButton_AdminPanel")
        self.progressBar_MainServerShared = QtGui.QProgressBar(self.tab_connection)
        self.progressBar_MainServerShared.setGeometry(QtCore.QRect(279, 11, 503, 25))
        self.progressBar_MainServerShared.setProperty("value", 0)
        self.progressBar_MainServerShared.setObjectName("progressBar_MainServerShared")
        self.pushButton_ConnDiscon = QtGui.QPushButton(self.tab_connection)
        self.pushButton_ConnDiscon.setGeometry(QtCore.QRect(0, 10, 85, 27))
        self.pushButton_ConnDiscon.setObjectName("pushButton_ConnDiscon")
        self.tabWidget.addTab(self.tab_connection, "")
        self.tab_shared = QtGui.QWidget()
        self.tab_shared.setObjectName("tab_shared")
        self.dockWidget_2 = QtGui.QDockWidget(self.tab_shared)
        self.dockWidget_2.setGeometry(QtCore.QRect(0, 0, 873, 251))
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_7 = QtGui.QWidget()
        self.dockWidgetContents_7.setObjectName("dockWidgetContents_7")
        self.gridLayout_9 = QtGui.QGridLayout(self.dockWidgetContents_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tableWidget_SharedFileByMySelf = QtGui.QTableWidget(self.dockWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_SharedFileByMySelf.sizePolicy().hasHeightForWidth())
        self.tableWidget_SharedFileByMySelf.setSizePolicy(sizePolicy)
        self.tableWidget_SharedFileByMySelf.setAcceptDrops(True)
        self.tableWidget_SharedFileByMySelf.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.tableWidget_SharedFileByMySelf.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.tableWidget_SharedFileByMySelf.setAlternatingRowColors(True)
        self.tableWidget_SharedFileByMySelf.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tableWidget_SharedFileByMySelf.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_SharedFileByMySelf.setColumnCount(7)
        self.tableWidget_SharedFileByMySelf.setObjectName("tableWidget_SharedFileByMySelf")
        self.tableWidget_SharedFileByMySelf.setColumnCount(7)
        self.tableWidget_SharedFileByMySelf.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedFileByMySelf.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedFileByMySelf.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedFileByMySelf.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedFileByMySelf.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedFileByMySelf.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedFileByMySelf.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedFileByMySelf.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_SharedFileByMySelf.setHorizontalHeaderItem(6, item)
        self.tableWidget_SharedFileByMySelf.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_SharedFileByMySelf.horizontalHeader().setDefaultSectionSize(120)
        self.gridLayout_9.addWidget(self.tableWidget_SharedFileByMySelf, 0, 0, 1, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_7)
        self.progressBar_Shared = QtGui.QProgressBar(self.tab_shared)
        self.progressBar_Shared.setGeometry(QtCore.QRect(536, 250, 176, 31))
        self.progressBar_Shared.setProperty("value", 0)
        self.progressBar_Shared.setObjectName("progressBar_Shared")
        self.comboBox_checkSums = QtGui.QComboBox(self.tab_shared)
        self.comboBox_checkSums.setGeometry(QtCore.QRect(718, 250, 155, 31))
        self.comboBox_checkSums.setObjectName("comboBox_checkSums")
        self.comboBox_checkSums.addItem("")
        self.comboBox_checkSums.setItemText(0, "sha512")
        self.comboBox_checkSums.addItem("")
        self.comboBox_checkSums.setItemText(1, "md5")
        self.comboBox_checkSums.addItem("")
        self.pushButton_DELALL = QtGui.QPushButton(self.tab_shared)
        self.pushButton_DELALL.setGeometry(QtCore.QRect(329, 250, 201, 31))
        self.pushButton_DELALL.setObjectName("pushButton_DELALL")
        self.pushButton_ADD = QtGui.QPushButton(self.tab_shared)
        self.pushButton_ADD.setGeometry(QtCore.QRect(0, 250, 158, 31))
        self.pushButton_ADD.setObjectName("pushButton_ADD")
        self.pushButton_Del = QtGui.QPushButton(self.tab_shared)
        self.pushButton_Del.setGeometry(QtCore.QRect(164, 250, 159, 31))
        self.pushButton_Del.setObjectName("pushButton_Del")
        self.tabWidget.addTab(self.tab_shared, "")
        self.tab_download = QtGui.QWidget()
        self.tab_download.setObjectName("tab_download")
        self.tableWidget_Download = QtGui.QTableWidget(self.tab_download)
        self.tableWidget_Download.setGeometry(QtCore.QRect(10, 0, 861, 168))
        self.tableWidget_Download.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.tableWidget_Download.setProperty("showDropIndicator", False)
        self.tableWidget_Download.setDragDropOverwriteMode(False)
        self.tableWidget_Download.setAlternatingRowColors(True)
        self.tableWidget_Download.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tableWidget_Download.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_Download.setColumnCount(9)
        self.tableWidget_Download.setObjectName("tableWidget_Download")
        self.tableWidget_Download.setColumnCount(9)
        self.tableWidget_Download.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Download.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Download.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Download.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Download.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Download.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Download.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Download.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Download.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Download.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Download.setHorizontalHeaderItem(8, item)
        self.tableWidget_Download.horizontalHeader().setDefaultSectionSize(120)
        self.pushButton_DELALL_Download = QtGui.QPushButton(self.tab_download)
        self.pushButton_DELALL_Download.setGeometry(QtCore.QRect(405, 220, 201, 31))
        self.pushButton_DELALL_Download.setObjectName("pushButton_DELALL_Download")
        self.pushButton_Del_Download = QtGui.QPushButton(self.tab_download)
        self.pushButton_Del_Download.setGeometry(QtCore.QRect(240, 220, 159, 31))
        self.pushButton_Del_Download.setObjectName("pushButton_Del_Download")
        self.tabWidget.addTab(self.tab_download, "")
        self.tab_options = QtGui.QWidget()
        self.tab_options.setObjectName("tab_options")
        self.dockWidget_Connect = QtGui.QDockWidget(self.tab_options)
        self.dockWidget_Connect.setGeometry(QtCore.QRect(0, 0, 170, 103))
        self.dockWidget_Connect.setAcceptDrops(False)
        self.dockWidget_Connect.setFloating(False)
        self.dockWidget_Connect.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_Connect.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_Connect.setObjectName("dockWidget_Connect")
        self.dockWidgetContents_10 = QtGui.QWidget()
        self.dockWidgetContents_10.setObjectName("dockWidgetContents_10")
        self.formLayout_2 = QtGui.QFormLayout(self.dockWidgetContents_10)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lineEdit_IP = QtGui.QLineEdit(self.dockWidgetContents_10)
        self.lineEdit_IP.setText("")
        self.lineEdit_IP.setMaxLength(16)
        self.lineEdit_IP.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_IP.setObjectName("lineEdit_IP")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lineEdit_IP)
        self.lineEdit_Port = QtGui.QLineEdit(self.dockWidgetContents_10)
        self.lineEdit_Port.setInputMask("")
        self.lineEdit_Port.setText("")
        self.lineEdit_Port.setMaxLength(8)
        self.lineEdit_Port.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Port.setObjectName("lineEdit_Port")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lineEdit_Port)
        self.dockWidget_Connect.setWidget(self.dockWidgetContents_10)
        self.dockWidget_ServAuth = QtGui.QDockWidget(self.tab_options)
        self.dockWidget_ServAuth.setGeometry(QtCore.QRect(0, 100, 164, 103))
        self.dockWidget_ServAuth.setFloating(False)
        self.dockWidget_ServAuth.setObjectName("dockWidget_ServAuth")
        self.dockWidgetContents_11 = QtGui.QWidget()
        self.dockWidgetContents_11.setObjectName("dockWidgetContents_11")
        self.gridLayout_5 = QtGui.QGridLayout(self.dockWidgetContents_11)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_Password = QtGui.QLineEdit(self.dockWidgetContents_11)
        self.lineEdit_Password.setText("")
        self.lineEdit_Password.setMaxLength(16)
        self.lineEdit_Password.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_Password.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.gridLayout_5.addWidget(self.lineEdit_Password, 1, 0, 1, 1)
        self.lineEdit_Login = QtGui.QLineEdit(self.dockWidgetContents_11)
        self.lineEdit_Login.setText("")
        self.lineEdit_Login.setMaxLength(16)
        self.lineEdit_Login.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Login.setObjectName("lineEdit_Login")
        self.gridLayout_5.addWidget(self.lineEdit_Login, 0, 0, 1, 1)
        self.dockWidget_ServAuth.setWidget(self.dockWidgetContents_11)
        self.dockWidget_Varuables = QtGui.QDockWidget(self.tab_options)
        self.dockWidget_Varuables.setGeometry(QtCore.QRect(310, 0, 190, 244))
        self.dockWidget_Varuables.setObjectName("dockWidget_Varuables")
        self.dockWidgetContents_12 = QtGui.QWidget()
        self.dockWidgetContents_12.setObjectName("dockWidgetContents_12")
        self.gridLayout_10 = QtGui.QGridLayout(self.dockWidgetContents_12)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_Debug_2 = QtGui.QGroupBox(self.dockWidgetContents_12)
        self.groupBox_Debug_2.setFlat(False)
        self.groupBox_Debug_2.setCheckable(False)
        self.groupBox_Debug_2.setChecked(False)
        self.groupBox_Debug_2.setObjectName("groupBox_Debug_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_Debug_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_7 = QtGui.QFrame(self.groupBox_Debug_2)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 0, 0, 1, 1)
        self.checkBox_Debug = QtGui.QCheckBox(self.groupBox_Debug_2)
        self.checkBox_Debug.setObjectName("checkBox_Debug")
        self.gridLayout_2.addWidget(self.checkBox_Debug, 1, 0, 1, 1)
        self.line_8 = QtGui.QFrame(self.groupBox_Debug_2)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.spinBox_TimeOut = QtGui.QSpinBox(self.groupBox_Debug_2)
        self.spinBox_TimeOut.setMinimum(1)
        self.spinBox_TimeOut.setObjectName("spinBox_TimeOut")
        self.horizontalLayout_3.addWidget(self.spinBox_TimeOut)
        self.label_2 = QtGui.QLabel(self.groupBox_Debug_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.line_9 = QtGui.QFrame(self.groupBox_Debug_2)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_2.addWidget(self.line_9, 4, 0, 1, 1)
        self.lineEdit_PathSharedFile = QtGui.QLineEdit(self.groupBox_Debug_2)
        self.lineEdit_PathSharedFile.setObjectName("lineEdit_PathSharedFile")
        self.gridLayout_2.addWidget(self.lineEdit_PathSharedFile, 5, 0, 1, 1)
        self.pushButton_Shared = QtGui.QPushButton(self.groupBox_Debug_2)
        self.pushButton_Shared.setObjectName("pushButton_Shared")
        self.gridLayout_2.addWidget(self.pushButton_Shared, 6, 0, 1, 1)
        self.line_10 = QtGui.QFrame(self.groupBox_Debug_2)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_2.addWidget(self.line_10, 7, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_Debug_2, 0, 0, 1, 1)
        self.dockWidget_Varuables.setWidget(self.dockWidgetContents_12)
        self.dockWidget_Validate = QtGui.QDockWidget(self.tab_options)
        self.dockWidget_Validate.setGeometry(QtCore.QRect(510, 0, 362, 173))
        self.dockWidget_Validate.setObjectName("dockWidget_Validate")
        self.dockWidgetContents_13 = QtGui.QWidget()
        self.dockWidgetContents_13.setObjectName("dockWidgetContents_13")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.dockWidgetContents_13)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line_11 = QtGui.QFrame(self.dockWidgetContents_13)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_4.addWidget(self.line_11)
        self.checkBox_ValidateFileBeforeSend = QtGui.QCheckBox(self.dockWidgetContents_13)
        self.checkBox_ValidateFileBeforeSend.setObjectName("checkBox_ValidateFileBeforeSend")
        self.verticalLayout_4.addWidget(self.checkBox_ValidateFileBeforeSend)
        self.checkBox_ValidateOnProgramStart = QtGui.QCheckBox(self.dockWidgetContents_13)
        self.checkBox_ValidateOnProgramStart.setObjectName("checkBox_ValidateOnProgramStart")
        self.verticalLayout_4.addWidget(self.checkBox_ValidateOnProgramStart)
        self.checkBox_CountHashWhenAdd = QtGui.QCheckBox(self.dockWidgetContents_13)
        self.checkBox_CountHashWhenAdd.setObjectName("checkBox_CountHashWhenAdd")
        self.verticalLayout_4.addWidget(self.checkBox_CountHashWhenAdd)
        self.checkBox_LetToDwnNoValidFiles = QtGui.QCheckBox(self.dockWidgetContents_13)
        self.checkBox_LetToDwnNoValidFiles.setObjectName("checkBox_LetToDwnNoValidFiles")
        self.verticalLayout_4.addWidget(self.checkBox_LetToDwnNoValidFiles)
        self.line_12 = QtGui.QFrame(self.dockWidgetContents_13)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_4.addWidget(self.line_12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.dockWidget_Validate.setWidget(self.dockWidgetContents_13)
        self.dockWidget_Save = QtGui.QDockWidget(self.tab_options)
        self.dockWidget_Save.setGeometry(QtCore.QRect(0, 200, 239, 81))
        self.dockWidget_Save.setObjectName("dockWidget_Save")
        self.dockWidgetContents_14 = QtGui.QWidget()
        self.dockWidgetContents_14.setObjectName("dockWidgetContents_14")
        self.gridLayout_11 = QtGui.QGridLayout(self.dockWidgetContents_14)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.buttonBox_Save = QtGui.QDialogButtonBox(self.dockWidgetContents_14)
        self.buttonBox_Save.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.buttonBox_Save.setStatusTip("")
        self.buttonBox_Save.setStandardButtons(QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.Save)
        self.buttonBox_Save.setCenterButtons(False)
        self.buttonBox_Save.setObjectName("buttonBox_Save")
        self.gridLayout_11.addWidget(self.buttonBox_Save, 0, 0, 1, 1)
        self.dockWidget_Save.setWidget(self.dockWidgetContents_14)
        self.tabWidget.addTab(self.tab_options, "")
        self.tab_ProjectSite = QtGui.QWidget()
        self.tab_ProjectSite.setObjectName("tab_ProjectSite")
        self.webView_ProjectSite = QtWebKit.QWebView(self.tab_ProjectSite)
        self.webView_ProjectSite.setGeometry(QtCore.QRect(0, 0, 873, 251))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView_ProjectSite.sizePolicy().hasHeightForWidth())
        self.webView_ProjectSite.setSizePolicy(sizePolicy)
        self.webView_ProjectSite.setAcceptDrops(False)
        self.webView_ProjectSite.setUrl(QtCore.QUrl("http://github.com/str0g/PAPServer"))
        self.webView_ProjectSite.setZoomFactor(0.699999988079)
        self.webView_ProjectSite.setObjectName("webView_ProjectSite")
        self.progressBar_Zoom = QtGui.QProgressBar(self.tab_ProjectSite)
        self.progressBar_Zoom.setGeometry(QtCore.QRect(440, 257, 433, 25))
        self.progressBar_Zoom.setMinimum(1)
        self.progressBar_Zoom.setMaximum(100)
        self.progressBar_Zoom.setProperty("value", 1)
        self.progressBar_Zoom.setObjectName("progressBar_Zoom")
        self.horizontalSlider_Zoom = QtGui.QSlider(self.tab_ProjectSite)
        self.horizontalSlider_Zoom.setGeometry(QtCore.QRect(0, 260, 434, 18))
        self.horizontalSlider_Zoom.setMouseTracking(True)
        self.horizontalSlider_Zoom.setMinimum(1)
        self.horizontalSlider_Zoom.setMaximum(100)
        self.horizontalSlider_Zoom.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Zoom.setObjectName("horizontalSlider_Zoom")
        self.tabWidget.addTab(self.tab_ProjectSite, "")
        self.dockWidget = QtGui.QDockWidget(self.centralwidget)
        self.dockWidget.setGeometry(QtCore.QRect(10, 330, 873, 221))
        self.dockWidget.setAutoFillBackground(False)
        self.dockWidget.setFloating(False)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget_console = QtGui.QListWidget(self.dockWidgetContents_4)
        self.listWidget_console.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listWidget_console.setTabKeyNavigation(False)
        self.listWidget_console.setProperty("showDropIndicator", False)
        self.listWidget_console.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listWidget_console.setMovement(QtGui.QListView.Snap)
        self.listWidget_console.setProperty("isWrapping", False)
        self.listWidget_console.setObjectName("listWidget_console")
        self.verticalLayout.addWidget(self.listWidget_console)
        self.dockWidget.setWidget(self.dockWidgetContents_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 887, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_SharedByServer.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lista Plików udostępnianych przez Serwer", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedByServer.setSortingEnabled(True)
        self.tableWidget_SharedByServer.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedByServer.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Pełna ścieżka", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedByServer.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Nazwa Pliku", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedByServer.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Rozmiar", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedByServer.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedByServer.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Suma kontrolna", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Search.setText(QtGui.QApplication.translate("MainWindow", "Szukaj", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Quit.setToolTip(QtGui.QApplication.translate("MainWindow", "Wyjście", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Quit.setText(QtGui.QApplication.translate("MainWindow", "Wyjście", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_UnMark.setText(QtGui.QApplication.translate("MainWindow", "Odznacz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DNSelected.setText(QtGui.QApplication.translate("MainWindow", "Pobierz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_AdminPanel.setText(QtGui.QApplication.translate("MainWindow", "Panel administracyjny", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ConnDiscon.setToolTip(QtGui.QApplication.translate("MainWindow", "Połącz/rozłacz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ConnDiscon.setText(QtGui.QApplication.translate("MainWindow", "Połącz", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_connection), QtGui.QApplication.translate("MainWindow", "Połączenie", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Udostępniane Pliki", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedFileByMySelf.setSortingEnabled(True)
        self.tableWidget_SharedFileByMySelf.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedFileByMySelf.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Pełna ścieżka", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedFileByMySelf.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Nazwa Pliku", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedFileByMySelf.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Rozmiar", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedFileByMySelf.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedFileByMySelf.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Suma kontrolna", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedFileByMySelf.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Pobierane", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_SharedFileByMySelf.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Ilosc klientów", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_checkSums.setToolTip(QtGui.QApplication.translate("MainWindow", "rsa512 bardzo bezpieczny jednak powolny \n"
"md5 już złamany jednak szybszy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_checkSums.setItemText(2, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DELALL.setToolTip(QtGui.QApplication.translate("MainWindow", "Wyczyść listę", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DELALL.setText(QtGui.QApplication.translate("MainWindow", "Wyczyść listę", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ADD.setToolTip(QtGui.QApplication.translate("MainWindow", "Dodaj pliki do listy udostępnionych", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ADD.setText(QtGui.QApplication.translate("MainWindow", "Dodaj", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Del.setToolTip(QtGui.QApplication.translate("MainWindow", "Usuń pliki z listy udostępnionych", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Del.setText(QtGui.QApplication.translate("MainWindow", "Usun", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_shared), QtGui.QApplication.translate("MainWindow", "Udostępnione", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_Download.setSortingEnabled(True)
        self.tableWidget_Download.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_Download.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Transfer", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_Download.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Pozostało", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_Download.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_Download.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Pełna ścieżka", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_Download.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Nazwa Pliku", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_Download.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rozmiar", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_Download.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_Download.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "Suma kontrolna", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DELALL_Download.setToolTip(QtGui.QApplication.translate("MainWindow", "Wyczyść listę", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DELALL_Download.setText(QtGui.QApplication.translate("MainWindow", "Wyczyść listę", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Del_Download.setToolTip(QtGui.QApplication.translate("MainWindow", "Usuń pliki z listy udostępnionych", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Del_Download.setText(QtGui.QApplication.translate("MainWindow", "Usun", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_download), QtGui.QApplication.translate("MainWindow", "Ściągane", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_Connect.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Adres Serwera", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_IP.setToolTip(QtGui.QApplication.translate("MainWindow", "Wprowadź login", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_ServAuth.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Autoryzacja", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Login.setToolTip(QtGui.QApplication.translate("MainWindow", "Wprowadź login", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Debug_2.setTitle(QtGui.QApplication.translate("MainWindow", "Zmienne", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Debug.setToolTip(QtGui.QApplication.translate("MainWindow", "Wyjście na konsole", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Debug.setText(QtGui.QApplication.translate("MainWindow", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Limit Czasu", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Shared.setText(QtGui.QApplication.translate("MainWindow", "Plik udostępnione", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_Validate.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Validacja i Sumy kontrolne", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ValidateFileBeforeSend.setText(QtGui.QApplication.translate("MainWindow", "Validuj plik przed wysłaniem", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ValidateOnProgramStart.setText(QtGui.QApplication.translate("MainWindow", "Validuj pliki przy starcie programu", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_CountHashWhenAdd.setText(QtGui.QApplication.translate("MainWindow", "Oblicz sumę kontroloną od przy dodaniu", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_LetToDwnNoValidFiles.setText(QtGui.QApplication.translate("MainWindow", "Pozwól ściągać pliki, które nie przeszły validacji", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_Save.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tu pojawi się wersja programu", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBox_Save.setToolTip(QtGui.QApplication.translate("MainWindow", "Resetuj przywróci ustawienia z przed zmiany", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_options), QtGui.QApplication.translate("MainWindow", "Opcje", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ProjectSite), QtGui.QApplication.translate("MainWindow", "Strona Projektu", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Konsola", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_console.setToolTip(QtGui.QApplication.translate("MainWindow", "Konsola", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
